# ============================================
# Profil PROD - Render + PostgreSQL
# Actif sur Render via SPRING_PROFILES_ACTIVE=prod
# ============================================

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Desactiver show-sql en production
spring.jpa.show-sql=false
