# =============================================
# Configuration Application Bancaire
# =============================================

# Server
server.port=8080
server.servlet.context-path=/api/v1

# =============================================
# Base de Données MySQL
# =============================================
#spring.datasource.url=jdbc:mysql://localhost:3306/banking_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =============================================
# Base de Données MySQL
# =============================================
spring.datasource.url=postgresql://banking_db:Ss8ptR9R501wq42Jg7LxJ0hCJ9XVx3hY@dpg-d7iedbvaqgkc739rua50-a/banking_db_v50c
spring.datasource.username=banking_db
spring.datasource.password=Ss8ptR9R501wq4
spring.datasource.driver-class-name=org.postgresql.Driver 


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =============================================
# Sécurité JWT
# =============================================
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=3600000
# Refresh token : 7 jours
app.jwt.refresh-expiration=604800000

# =============================================
# Swagger / OpenAPI
# =============================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# =============================================
# Logging
# =============================================
logging.level.com.banking=DEBUG
logging.level.org.springframework.security=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
